from turtle import *
from math import sqrt

def przesun(x, y):
    up()
    fd(x)
    lt(90)
    fd(y)
    rt(90)
    down()

def kwadrat4():
    przesun(-48, -48)
    for i in range(1, 5, 1):
        fillcolor('black')
        begin_fill()
        lt(45)
        fd(32/sqrt(2))
        rt(90)
        fd(32/sqrt(2))
        lt(45)
        end_fill()
        lt(45)
        fillcolor('black')
        begin_fill()
        fd(32*sqrt(2))
        rt(135)
        fd(32)
        rt(90)
        fd(32)
        rt(135)
        fd(32*sqrt(2))
        lt(45)
        end_fill()
    przesun(0, 32)
    fillcolor('black')
    begin_fill()
    for i in range(1, 5, 1):
        fd(32)
        lt(90)
    end_fill()
    przesun(16, 16)

def kwadrat5():
    przesun(-80, -80)
    for i in range(1, 5, 1):
        fd(160)
        lt(90)
    fd(32)
    for i in range(1, 5, 1):
        for j in range(1, 4, 1):
            fillcolor('black')
            begin_fill()
            lt(45)
            fd(32/sqrt(2))
            rt(90)
            fd(32/sqrt(2))
            lt(45)
            end_fill()
        lt(45)
        fillcolor('black')
        begin_fill()
        fd(32*sqrt(2))
        rt(135)
        fd(32)
        rt(90)
        fd(32)
        rt(135)
        fd(32*sqrt(2))
        lt(45)
        end_fill()
    przesun(32, 32)
    for i in range(1, 5, 1):
        fillcolor('black')
        begin_fill()
        lt(45)
        fd(32/sqrt(2))
        rt(90)
        fd(32/sqrt(2))
        lt(45)
        end_fill()
        lt(45)
        fillcolor('black')
        begin_fill()
        fd(32*sqrt(2))
        rt(135)
        fd(32)
        rt(90)
        fd(32)
        rt(135)
        fd(32*sqrt(2))
        lt(45)
        end_fill()
    przesun(0, 32)
    fillcolor('black')
    begin_fill()
    for i in range(1, 5, 1):
        fd(32)
        lt(90)
    end_fill()
    przesun(16, 16)

def pasek_skrajny():
    kwadrat5()
    przesun(192, 0)
    kwadrat4()
    przesun(160, 0)
    kwadrat5()

def pasek_srodkowy():
    kwadrat4()
    przesun(160, 0)
    kwadrat5()
    przesun(192, 0)
    kwadrat4()

def motyw():
    pasek_skrajny()
    przesun(-288, -160)
    pasek_srodkowy()
    przesun(-320, -160)
    pasek_skrajny()
    przesun(-400, -80)
    for i in range(1, 5, 1):
        fd(480)
        lt(90)

przesun(-200, 200)
tracer(0)
motyw()
update()
done()