from turtle import *
from math import sqrt

def przesun(x, y):
    up()
    fd(x)
    lt(90)
    fd(y)
    rt(90)
    down()

def czesc_ramki(a):
    fillcolor('black')
    begin_fill()
    fd(4*a)
    lt(90)
    fd(a)
    lt(90)
    fd(3*a)
    lt(45)
    fd(a*sqrt(2))
    lt(135)
    end_fill()
    przesun(3*a, 7*a)
    fillcolor('black')
    begin_fill()
    fd(2*a)
    rt(90)
    fd(7*a)
    lt(135)
    fd(a*sqrt(2))
    lt(45)
    fd(7*a)
    lt(90)
    fd(2*a)
    lt(45)
    fd(a*sqrt(2))
    end_fill()
    lt(135)
    przesun(0, -(a))
    fillcolor('black')
    begin_fill()
    rt(90)
    fd(4*a)
    lt(135)
    fd(a*sqrt(2))
    lt(45)
    fd(3*a)
    lt(90)
    fd(a)
    lt(180)
    end_fill()
    przesun(-(3*a), -(4*a))
    fillcolor('black')
    begin_fill()
    fd(2*a)
    lt(90)
    fd(a)
    lt(90)
    fd(a)
    rt(90)
    fd(7*a)
    lt(90)
    fd(a)
    lt(90)
    fd(8*a)
    lt(180)
    fd(8*a)
    rt(90)
    end_fill()

def rog_ramki(a):
    czesc_ramki(a)
    fillcolor('black')
    begin_fill()
    for i in range(1, 3, 1):
        fd(7*a)
        rt(90)
        fd(a)
        rt(90)
    end_fill()
    fd(7*a)
    rt(90)

def rama(n):
    a = 480/((11*n)+8)
    for i in range(1, 5, 1):
        for i in range(1, n, 1):
            czesc_ramki(a)
            przesun(0, a)
        rog_ramki(a)
        przesun(0, a)
    


n = int(input("Podaj n: "))
przesun(-200, -200)
tracer(0)
rama(n)
update()
done()