from turtle import *
from math import sqrt

def przesun(x, y):
    up()
    fd(x)
    lt(90)
    fd(y)
    rt(90)
    down()

def rys0(a):
    lt(45)
    fd(2*a*sqrt(2))
    rt(45)
    przesun(-2*a, 0)
    rt(45)
    fd(2*a*sqrt(2))
    lt(45)
    przesun(-2*a, 0)

def rys1(a):
    lt(45)
    fd(2*a*sqrt(2))
    rt(45)
    przesun(-2*a, 0)
    rt(45)
    fd(2*a*sqrt(2))
    lt(45)
    przesun(-2*a, 0)
    lt(90)
    fd(2*a)
    bk(2*a)
    rt(90)

def rys2(a):
    lt(45)
    fd(2*a*sqrt(2))
    rt(45)
    przesun(-2*a, 0)
    rt(45)
    fd(2*a*sqrt(2))
    lt(45)
    przesun(-2*a, 0)
    lt(90)
    fd(2*a)
    bk(2*a)
    rt(90)
    przesun(2*a, 0)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-2*a, -2*a)

def rys3(a):
    lt(45)
    fd(2*a*sqrt(2))
    rt(45)
    przesun(-2*a, 0)
    rt(45)
    fd(2*a*sqrt(2))
    lt(45)
    przesun(-2*a, 0)
    lt(90)
    fd(2*a)
    bk(2*a)
    rt(90)
    przesun(2*a, 0)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a, -2*a)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a, -2*a)

def rys4(a):
    lt(45)
    fd(2*a*sqrt(2))
    rt(45)
    przesun(-2*a, 0)
    rt(45)
    fd(2*a*sqrt(2))
    lt(45)
    przesun(-2*a, 0)
    lt(90)
    fd(2*a)
    bk(2*a)
    rt(90)
    przesun(2*a, 0)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a, -2*a)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a, -2*a)
    fd(2*a)
    bk(2*a)

def rys5(a):
    lt(45)
    fd(2*a*sqrt(2))
    rt(45)
    przesun(-2*a, 0)
    rt(45)
    fd(2*a*sqrt(2))
    lt(45)
    przesun(-2*a, 0)
    lt(90)
    fd(2*a)
    bk(2*a)
    rt(90)
    przesun(2*a, 0)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a, -2*a)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a, -2*a)
    fd(2*a)
    bk(2*a)
    przesun(0, 2*a)
    fd(2*a)
    przesun(-2*a, -2*a)

def rys6(a):
    lt(45)
    fd(2*a*sqrt(2))
    rt(45)
    przesun(-2*a, 0)
    rt(45)
    fd(2*a*sqrt(2))
    lt(45)
    przesun(-2*a, 0)
    lt(90)
    fd(2*a)
    bk(2*a)
    rt(90)
    przesun(2*a, 0)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a, -2*a)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a, -2*a)
    fd(2*a)
    bk(2*a)
    przesun(0, 2*a)
    fd(2*a)
    przesun(-2*a, -a)
    fd(2*a)
    przesun(-2*a, -a)
   
def rys7(a):
    lt(45)
    fd(2*a*sqrt(2))
    rt(45)
    przesun(-2*a, 0)
    rt(45)
    fd(2*a*sqrt(2))
    lt(45)
    przesun(-2*a, 0)
    lt(90)
    fd(2*a)
    bk(2*a)
    rt(90)
    przesun(2*a, 0)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a, -2*a)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a, -2*a)
    fd(2*a)
    bk(2*a)
    przesun(0, 2*a)
    fd(2*a)
    przesun(-2*a, -a)
    fd(2*a)
    przesun(-2*a, -a)
    fd(a/2)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a/2, -2*a)

def rys8(a):
    lt(45)
    fd(2*a*sqrt(2))
    rt(45)
    przesun(-2*a, 0)
    rt(45)
    fd(2*a*sqrt(2))
    lt(45)
    przesun(-2*a, 0)
    lt(90)
    fd(2*a)
    bk(2*a)
    rt(90)
    przesun(2*a, 0)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a, -2*a)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a, -2*a)
    fd(2*a)
    bk(2*a)
    przesun(0, 2*a)
    fd(2*a)
    przesun(-2*a, -a)
    fd(2*a)
    przesun(-2*a, -a)
    fd(a/2)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-a/2, -2*a)
    fd(1.5*a)
    lt(90)
    fd(2*a)
    rt(90)
    przesun(-1.5*a, -2*a)

def rys9(a):
    for i in range(0, 2, 1):
        fd(a)
        lt(90)
        fd(2*a)
        lt(90)

def OL(s):
    if ('9' in s):
        a = 720/(3*len(s)-1 + 1)
    else:
        a = 720/(3*len(s)-1 + 2)
    przesun(-360, 0)
    for i in range(0, len(s), 1):
        if (s[i] == '0'):
            rys0(a)
            przesun(3*a, 0)
        elif (s[i] == '1'):
            rys1(a)
            przesun(3*a, 0)
        elif (s[i] == '2'):
            rys2(a)
            przesun(3*a, 0)
        elif (s[i] == '3'):
            rys3(a)
            przesun(3*a, 0)
        elif (s[i] == '4'):
            rys4(a)
            przesun(3*a, 0)
        elif (s[i] == '5'):
            rys5(a)
            przesun(3*a, 0)
        elif (s[i] == '6'):
            rys6(a)
            przesun(3*a, 0)
        elif (s[i] == '7'):
            rys7(a)
            przesun(3*a, 0)
        elif (s[i] == '8'):
            rys8(a)
            przesun(3*a, 0)
        elif (s[i] == '9'):
            rys9(a)
            przesun(2*a, 0)

tracer(0)
OL('0123456789')
hideturtle()
update()
done()

    